vidaud/seta

- .gitignore
- seta-compose/docker-compose-dev.yml
- seta-react/Dockerfile-dev
- seta-react/changelog.txt
seta-react-ui container builds on both windows and linux systems - see changelog
> seta-react-ui container

- seta-nginx/project.conf
- seta-ui/seta-flask-server/blueprints/communities/__init__.py
- seta-ui/seta-flask-server/blueprints/communities/community.py
- seta-ui/seta-flask-server/blueprints/communities/resource.py
- seta-ui/seta-flask-server/blueprints/token_auth.py
- seta-ui/seta-flask-server/dependency.py
- seta-ui/seta-flask-server/factory.py
- seta-ui/seta-flask-server/infrastructure/decorators.py
- seta-ui/seta-flask-server/repository/interfaces/__init__.py
- seta-ui/seta-flask-server/repository/interfaces/communities_broker.py
- seta-ui/seta-flask-server/repository/interfaces/resources_broker.py
- seta-ui/seta-flask-server/repository/mongo_implementation/__init__.py
- seta-ui/seta-flask-server/repository/mongo_implementation/db_communities_broker.py
- seta-ui/seta-flask-server/repository/mongo_implementation/db_resources_broker.py
Initial setup for communities api
> Communities api init

- seta-data/src/app.py
- seta-data/src/config.py
> seta-data app refactor

- seta-ui/Dockerfile
- seta-ui/Dockerfile-dev-flask
- seta-ui/app_dev.py
- seta-ui/changelog.txt
- seta-ui/seta_flask_server/config.py
- seta-ui/seta_flask_server/config_test.py
- seta-ui/seta_flask_server/factory.py
- seta-ui/tests/conftest.py
Document config options in seta-ui and remove unnecessary ones
> Config refactoring

- seta-api/apis/corpus/corpus.py
- seta-api/infrastructure/auth_validator.py
Throw 403 error when the list of view permissions is empty
> Fix resource authorization

- seta-api/Dockerfile-dev-flask
- seta-api/app_dev.py
- seta-api/config.py
- seta-api/factory.py
Reorganize and document config properties
> seta-api config refactor

- seta-api/Dockerfile-test
- seta-api/app_dev.py
- seta-api/app_test.py
- seta-api/seta_api/config.py
- seta-api/seta_api/factory.py
- seta-api/seta_api/infrastructure/log_setup.py
- seta-compose-test/docker-compose.yml
- seta-compose/docker-compose-dev.yml
- seta-data/Dockerfile-test
- seta-data/src/app.py
- seta-data/src/config.py
- seta-es/Dockerfile-test
- seta-mongo/Dockerfile-test
- seta-nginx/Dockerfile-dev
- seta-nginx/Dockerfile-test
- seta-nginx/project.conf
- seta-nginx/project_dev.conf
- seta-nginx/project_test.conf
- seta-ui/Dockerfile-test
- seta-ui/app_test.py
- seta-ui/seta_flask_server/config_test.py
- seta-ui/seta_flask_server/factory.py
- seta-ui/seta_flask_server/infrastructure/log_setup.py
- seta-ui/tests/conftest.py
New docker containers for test
> Docker testing env

- seta-compose/README.md
- seta-compose/dev-build.bat
- seta-compose/dev-up.bat
Add batch scripts for development.
Update readme file
> Batch scripts

- seta-auth/seta_auth/config.py
- seta-ui/seta_flask_server/config.py
- seta-ui/seta_flask_server/infrastructure/clients/cas_client.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_users_broker.py
Fix read of the secret key
Fix case-insensitive provider
> Fix case-insensitive provider name

- seta-react/src/components/AppRouter/AppRouter.tsx
- seta-react/src/pages/SearchWithFilters/SearchWithFilters.tsx
- seta-react/src/pages/SearchWithFilters/components/ApplyFilters/ApplyFilters.tsx
- seta-react/src/pages/SearchWithFilters/components/ApplyFilters/index.ts
- seta-react/src/pages/SearchWithFilters/components/DataSourceFilter/DataSourceFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/DataSourceFilter/index.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/index.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/SidePanel/SidePanel.tsx
- seta-react/src/pages/SearchWithFilters/components/SidePanel/index.ts
- seta-react/src/pages/SearchWithFilters/components/TaxonomyFilter/TaxonomyFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/TaxonomyFilter/index.ts
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/index.ts
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/index.ts
- seta-react/src/pages/SearchWithFilters/custom/array_diffs.tsx
- seta-react/src/pages/SearchWithFilters/custom/map-filters.tsx
- seta-react/src/pages/SearchWithFilters/custom/map-query.tsx
- seta-react/src/pages/SearchWithFilters/custom/tree-styles.tsx
- seta-react/src/pages/SearchWithFilters/index.ts
- seta-react/src/pages/SearchWithFilters/samples/aggregations-01.ts
- seta-react/src/pages/SearchWithFilters/samples/aggregations-02.ts
- seta-react/src/pages/SearchWithFilters/types/contracts.tsx
- seta-react/src/pages/SearchWithFilters/types/filters.tsx
- seta-ui/seta_flask_server/infrastructure/clients/cas_client.py
Add advanced filter components for the search page.
Test the component at http://localhost/search-with-filters
> Advanced filters for the search page

- seta-react/src/components/AppRouter/AppRouter.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
Fixes for previously applied filters
> Add indicators for modified filters

- seta-api/seta_api/apis/corpus/corpus_response.py
Move return documents outside for
> Fix handle_aggs_response

- seta-react/src/api/search/related-clusters.ts
- seta-react/src/api/search/related-terms.ts
- seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/TaxonomyTree/TaxonomyTree.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/custom/map-filters.ts
- seta-react/src/pages/SearchWithFilters/custom/map-query.ts
- seta-react/src/pages/SearchWithFilters/types/contracts.ts
- seta-react/src/services/corpus/ontology-list.service.ts
* param 'terms' instead of 'term' for ontology-list and similar
* prevent render for TaxonomyNode when node is null
* fix year range query filter
> Fix some calls to seta-api

- seta-api/seta_api/apis/embeddings/embeddings.py
- seta-api/seta_api/apis/embeddings/embeddings_logic.py
- seta-api/seta_api/infrastructure/utils/embeddings.py
"embeddings" part of the response to be removed once switch to the "embedding with chunk" is done.
> embedding with chunk text added to api response

- seta-api/seta_api/infrastructure/seta_jwt_manager.py
- seta-auth/seta_auth/blueprints/token_info.py
- seta-react/src/pages/SearchWithFilters/components/DataSourceFilter/DataSourceFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/FilterInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/MultipleValuesInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/RangeValueInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/TextChunkInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/utils.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useClearFilter.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/utils.ts
- seta-react/src/pages/SearchWithFilters/components/TaxonomyFilter/TaxonomyFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/custom/map-filters.ts
- seta-react/src/pages/SearchWithFilters/types/filters.ts
Fix reversion of the deleted filters.
Enlarge badges and buttons sizes
> Fixes for search filters on hovercard

- seta-react/src/components/Breadcrumbs/Breadcrumbs.tsx
- seta-react/src/components/Breadcrumbs/styles.ts
- seta-react/src/components/Page/Page.tsx
- seta-react/src/layouts/CommunityLayout/CommunityLayout.tsx
- seta-react/src/pages/SearchPageNew/SearchPageNew.tsx
- seta-react/src/pages/SearchWithFilters/components/ApplyFilters/ApplyFilters.tsx
- seta-react/src/pages/SearchWithFilters/components/ApplyFilters/styles.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useClearFilter.ts
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/styles/global-styles.ts
- seta-react/src/types/breadcrumbs.ts
- Update the Breadcrumbs component
- Update general styling for documents and filters
- Fix a few issues
> [seta-react] Update Breadcrumbs & styling

- seta-api/Dockerfile
- seta-api/Dockerfile-dev-flask
- seta-api/Dockerfile-test
- seta-api/requirements.txt
- seta-api/seta_api/apis/file_to_text/file_to_text.py
- seta-api/seta_api/apis/file_to_text/file_to_text_logic.py
it uses temporary folder and delete it after detecting mime type. 
New library "python-magic" used, it required to add a line (for libmagic-dev) on dockerfile and a line on api requirements.txt
> Development seta api file to text temporary folder

- seta-react/package.json
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/FilterInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/MultipleValuesInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/TinyChart.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/utils.ts
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/custom/map-filters.ts
- seta-react/src/pages/SearchWithFilters/types/filter-data.ts
Add tiny charts for aggregations
Fix years range in hover card
> Add tiny charts for filters

- seta-auth/seta_auth/repository/mongo_implementation/db_resources_broker.py
- seta-ui/seta_flask_server/blueprints/auth_ecas.py
- seta-ui/seta_flask_server/blueprints/auth_github.py
- seta-ui/seta_flask_server/blueprints/profile/__init__.py
- seta-ui/seta_flask_server/blueprints/profile/models/resources_dto.py
- seta-ui/seta_flask_server/blueprints/profile/models/scopes_dto.py
- seta-ui/seta_flask_server/blueprints/profile/resources.py
- seta-ui/seta_flask_server/dependency.py
- seta-ui/seta_flask_server/repository/interfaces/__init__.py
- seta-ui/seta_flask_server/repository/interfaces/user_profile.py
- seta-ui/seta_flask_server/repository/models/__init__.py
- seta-ui/seta_flask_server/repository/models/seta_user.py
- seta-ui/seta_flask_server/repository/models/seta_user_ext.py
- seta-ui/seta_flask_server/repository/models/user_profile.py
- seta-ui/seta_flask_server/repository/mongo_implementation/__init__.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_apps_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_resources_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_user_profile.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_users_broker.py
- seta-ui/tests/functional/profile/test_unsearchables.py
- seta-ui/tests/infrastructure/helpers/profile.py
Profile api endpoints for managing restricted resource (see http://localhost/seta-ui/api/v1/me/doc -> Restricted resources)
Build queryable resources filtering out the restricted list
Add extension class for SetaUser model
> [seta-ui, seta-auth] User profile for search restricted resources

- seta-ui/seta_flask_server/blueprints/communities/community.py
- seta-ui/seta_flask_server/blueprints/communities/community_change_requests.py
- seta-ui/seta_flask_server/blueprints/communities/community_invite.py
- seta-ui/seta_flask_server/blueprints/communities/community_membership.py
- seta-ui/seta_flask_server/blueprints/communities/community_membership_request.py
- seta-ui/seta_flask_server/blueprints/communities/community_my_membership.py
- seta-ui/seta_flask_server/blueprints/communities/community_permissions.py
- seta-ui/seta_flask_server/blueprints/communities/community_resources.py
- seta-ui/seta_flask_server/blueprints/communities/discovery.py
- seta-ui/seta_flask_server/blueprints/communities/helpers/scopes_helper.py
- seta-ui/seta_flask_server/blueprints/communities/invites.py
- seta-ui/seta_flask_server/blueprints/communities/models/invite_dto.py
- seta-ui/seta_flask_server/blueprints/communities/models/membership_dto.py
- seta-ui/seta_flask_server/blueprints/communities/models/permissions_dto.py
- seta-ui/seta_flask_server/blueprints/communities/resource.py
- seta-ui/seta_flask_server/blueprints/communities/resource_change_request.py
- seta-ui/seta_flask_server/blueprints/communities/resource_permissions.py
- seta-ui/seta_flask_server/blueprints/profile/resources.py
- seta-ui/seta_flask_server/blueprints/profile/rsa.py
- seta-ui/seta_flask_server/infrastructure/constants.py
- seta-ui/tests/functional/communities/test_community_story.py
- seta-ui/tests/infrastructure/helpers/resource_permission.py
Add detail description for community api endpoints.
Adjust permission validation for community apis
Update tests for community story
> [seta-ui] Update internal api documentation. Manage community ownership

- seta-data/requirements.txt
- seta-data/src/app.py
Processing large JSON files in Python using ijson library.
> Processing large JSON file

- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/TermsSuggestions.tsx
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/EnrichInfo/EnrichInfo.tsx
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OntologyHeader/OntologyHeader.tsx
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OntologyHeader/styles.ts
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OperatorInfo/OperatorInfo.tsx
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OperatorInfo/index.ts
- seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OperatorInfo/styles.ts
- seta-react/src/pages/SearchPageNew/components/TokensInput/TokensInput.tsx
- seta-react/src/pages/SearchPageNew/components/TokensInput/components/TokensInfo/TokensInfo.tsx
- seta-react/src/pages/SearchPageNew/components/TokensInput/hooks/use-tokens.tsx
- seta-react/src/pages/SearchPageNew/components/TokensInput/styles.ts
- seta-react/src/pages/SearchPageNew/types/token.ts
- seta-react/src/utils/search-utils.ts
This PR introduces the `AND` (and `OR`) operator for search query, including for enriched terms.
> [react-react] Add AND operator for search query

- seta-react/src/components/AppRouter/components/RequireAuth.tsx
- seta-react/src/pages/LoginPage/LoginPage.tsx
- seta-ui/seta_flask_server/blueprints/auth_ecas.py
- seta-ui/seta_flask_server/blueprints/auth_github.py
- seta-ui/seta_flask_server/factory.py
- seta-ui/seta_flask_server/infrastructure/auth_helpers.py
- seta-ui/seta_flask_server/infrastructure/clients/cas_client.py
Redirect to the absolute path specified by the 'redirect' query param
> Redirect to url after authentication

- seta-compose/docker-compose-test.yml
- seta-ui/migrations/README.md
- seta-ui/migrations/catalogues/roles_catalogue_builder.py
- seta-ui/migrations/catalogues/scopes_catalogue_builder.py
- seta-ui/seta_flask_server/blueprints/communities/community_membership.py
- seta-ui/seta_flask_server/repository/interfaces/catalogue_broker.py
- seta-ui/seta_flask_server/repository/interfaces/membership_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_catalogue_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_community_invites_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_membership_broker.py
Fix db migration, downgrade and migrate again.
Run in the terminal of the ***seta-ui*** docker container:
MONGODB_MIGRATIONS_CONFIG=migrations/config.ini mongodb-migrate --downgrade
MONGODB_MIGRATIONS_CONFIG=migrations/config.ini mongodb-migrate
> No community scopes for new members

- seta-ui/seta_flask_server/blueprints/admin/__init__.py
- seta-ui/seta_flask_server/blueprints/admin/change_requests.py
- seta-ui/seta_flask_server/blueprints/admin/models/change_request_dto.py
- seta-ui/seta_flask_server/blueprints/communities/community_change_requests.py
- seta-ui/seta_flask_server/blueprints/communities/models/community_dto.py
- seta-ui/seta_flask_server/blueprints/communities/models/models_dto.py
- seta-ui/seta_flask_server/blueprints/communities/models/resource_request_dto.py
- seta-ui/seta_flask_server/blueprints/communities/resource_change_request.py
- seta-ui/seta_flask_server/factory.py
- seta-ui/tests/functional/communities/test_change_requests.py
- seta-ui/tests/infrastructure/helpers/admin_change_requests.py
- seta-ui/tests/infrastructure/helpers/community_change_request.py
- seta-ui/tests/infrastructure/helpers/resource_change_request.py
Change request administration moved from communities to new admin blueprint (swagger doc at http://localhost/seta-ui/api/admin/doc)
> UI admin requests

- seta-react/src/pages/HomePage/HomePage.tsx
- seta-react/src/pages/HomePage/components/modal/ModalPage.tsx
setup of local cookie for get started button (presentation)
> UI home page3

- seta-api/seta_api/apis/corpus/corpus_logic.py
- seta-api/seta_api/apis/corpus/variables.py
- seta-api/seta_api/private/resources.py
- seta-api/seta_api/private/resources_logic.py
- new endpoint for private api /seta-api-private/v1/resource/all
- num_chunks added to corpus/document/{id}
> private resource all api and num_chunks for corpus

- seta-ui/seta_flask_server/blueprints/admin/__init__.py
- seta-ui/seta_flask_server/blueprints/admin/models/orphans_dto.py
- seta-ui/seta_flask_server/blueprints/admin/orphans.py
- seta-ui/seta_flask_server/infrastructure/clients/private_api_client.py
- seta-ui/seta_flask_server/repository/interfaces/communities_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_communities_broker.py
Add endpoints for managing 'orphan' entities in sysadmin api
> Community orphans

- seta-react/src/pages/SearchWithFilters/components/FilterInfo/FilterInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/RangeValueInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/TextChunkInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/styles.ts
- seta-react/src/pages/SearchWithFilters/components/TextChunkFilter/TextChunkFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/types/filter-info.ts
Show multiple chunks filter: 
* false: CHUNK_SEARCH
* true: ALL_CHUNKS
> Text chunk filter as slider

- seta-react/src/api/admin/orphaned-communities.ts
- seta-react/src/api/admin/orphaned-resources.ts
- seta-react/src/api/admin/query-keys.ts
- seta-react/src/api/admin/users.ts
- seta-react/src/pages/Admin/CommunityRequests/CommunityRequests.tsx
- seta-react/src/pages/Admin/OrphanedCommunities/OrphanedCommunities.tsx
- seta-react/src/pages/Admin/OrphanedCommunities/components/OrphanesTable/OrphanesTable.tsx
- seta-react/src/pages/Admin/OrphanedCommunities/components/OrphanesTable/index.ts
- seta-react/src/pages/Admin/OrphanedCommunities/components/OwnerForm/OwnerForm.tsx
- seta-react/src/pages/Admin/OrphanedCommunities/components/OwnerForm/index.ts
- seta-react/src/pages/Admin/OrphanedResources/OrpahnedResources.tsx
- seta-react/src/types/admin/change-requests.ts
- seta-react/src/types/admin/community.ts
- seta-react/src/types/admin/user-info.ts
- seta-ui/seta_flask_server/blueprints/admin/__init__.py
- seta-ui/seta_flask_server/blueprints/admin/models/orphans_dto.py
- seta-ui/seta_flask_server/blueprints/admin/models/users_dto.py
- seta-ui/seta_flask_server/blueprints/admin/orphans.py
- seta-ui/seta_flask_server/blueprints/admin/users.py
- seta-ui/seta_flask_server/blueprints/profile/info.py
- seta-ui/seta_flask_server/repository/interfaces/users_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_users_broker.py
Web app:
http://localhost/admin/orphaned-communities
http://localhost/admin/orphaned-resources
Web api:
http://localhost/seta-ui/api/v1/admin/doc
> Orphaned communities and resources - list and edit UIs

- seta-ui/seta_flask_server/blueprints/profile/__init__.py
- seta-ui/seta_flask_server/blueprints/profile/library.py
- seta-ui/seta_flask_server/blueprints/profile/logic/library_logic.py
- seta-ui/seta_flask_server/blueprints/profile/models/library_dto.py
- seta-ui/seta_flask_server/dependency.py
- seta-ui/seta_flask_server/infrastructure/helpers.py
- seta-ui/seta_flask_server/repository/interfaces/__init__.py
- seta-ui/seta_flask_server/repository/interfaces/library_broker.py
- seta-ui/seta_flask_server/repository/models/__init__.py
- seta-ui/seta_flask_server/repository/models/library.py
- seta-ui/seta_flask_server/repository/mongo_implementation/__init__.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_library_broker.py
Documentation at **http://localhost/seta-ui/api/v1/me/doc**, Library section
> User Library API

- seta-auth/seta_auth/blueprints/logic/token_info_logic.py
- seta-auth/seta_auth/blueprints/token_info.py
- seta-auth/seta_auth/infrastructure/constants.py
- seta-auth/seta_auth/repository/interfaces/resources_broker.py
- seta-auth/seta_auth/repository/mongo_implementation/db_resources_broker.py
**/authorization/v1/token_info** returns resource permissions depending on the resource type:
* 'view' if type is 'discoverable'
* new entry 'representatives' if  type is 'representative'
> Get user permissions by resource type

- seta-ui/seta_flask_server/blueprints/profile/library.py
- seta-ui/seta_flask_server/blueprints/profile/logic/library_logic.py
- seta-ui/seta_flask_server/repository/models/library.py
Return created items including generated id on POST /me/library
> Return created item

- seta-react/src/pages/SearchWithFilters/components/FilterInfo/FilterInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FilterInfo/RangeValueInfo.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useClearFilter.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/useFilter.ts
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/utils.ts
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/YearsRangeFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/YearsRangeFilter/utils.ts
- seta-react/src/pages/SearchWithFilters/types/filter-info.ts
- seta-react/src/pages/SearchWithFilters/types/filters.ts
Remove switch - date filter is always enabled
Add 'clear filter' action on info popover
> Refactor date filter on search page

- seta-auth/requirements.txt
- seta-ui/requirements.txt
Run dev-build to install the new version of flask-restx in the web server containers
> Update flask-restx version

- seta-react/src/components/PopupOverlay/styles.ts
- seta-react/src/pages/SearchPageNew/components/documents/StagedDocsPopup/components/StagedDocInfo/StagedDocInfo.tsx
- seta-react/src/pages/SearchPageNew/components/documents/StagedDocsPopup/components/StagedDocInfo/styles.ts
This PR resolves the Staged Documents popup overflow on smaller screen when it contains documents with long names.
> [seta-react] Fix Staged Documents popup overflow

- seta-ui/seta_flask_server/blueprints/profile/info.py
- seta-ui/seta_flask_server/blueprints/profile/models/info_dto.py
Check http://localhost/seta-ui/api/v1/me/doc:
* /me
* /me/user-info
> Add 'domain' prop for user info

- seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-delete-modal.tsx
- seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-move-modal.tsx
- seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-node-events.tsx
- seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-rename-modal.tsx
- seta-react/src/pages/SearchPageNew/components/documents/SaveDocumentsModal/SaveDocumentsModal.tsx
- seta-react/src/pages/SearchPageNew/hooks/use-save-docs-modal.tsx
This PR adds info/success/error notifications using the recently introduced notification utils for all the Library operations.
> [seta-react] Add library notifications

- seta-config/ui.conf
- seta-ui/seta_flask_server/blueprints/authentication/auth.py
- seta-ui/seta_flask_server/blueprints/authorization/token_auth.py
- seta-ui/seta_flask_server/config.py
Important fix for configured token expiration times!
> Fix authentication config and token_auth url

- seta-react/src/api/search/chunks.ts
This PR changes the API call for getting chunks to POST.
> [seta-react] Change chunks API call to POST

- seta-react/src/components/Accordion/AccordionItem.tsx
- seta-react/src/components/Accordion/AccordionPanel.tsx
- seta-react/src/hooks/use-scrolled.ts
- seta-react/src/pages/SearchWithFilters/components/DataSourceFilter/DataSourceFilter.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/TinyChart.tsx
- seta-react/src/pages/SearchWithFilters/components/FiltersPanel/styles.ts
- seta-react/src/pages/SearchWithFilters/custom/tree-styles.ts
- seta-react/src/styles/keyframe-animations.ts
This PR updates the styling of the Filters panel and Sources Tree areas.
> [seta-react] Improve filters UI

- seta-react/src/libs/axios-error-interceptor.ts
- seta-ui/seta_flask_server/blueprints/profile/__init__.py
- seta-ui/seta_flask_server/blueprints/profile/models/rsa_dto.py
- seta-ui/seta_flask_server/blueprints/profile/rsa_key.py
**/me/rsa-key** endpoint
Check http://localhost/seta-ui/api/v1/me/doc, User RSA Key Pair namespace
> New implementation for the user rsa-key api

- seta-react/src/hooks/use-highlight.tsx
- seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/DocumentInfo.tsx
- seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/ChunkPreview/ChunkPreview.tsx
- seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/DocumentChunks/DocumentChunks.tsx
This PR changes search results highlights to match full words only.
> [seta-react] Add full word highlight for Search results

- seta-compose/README.md
Instructions for  creating .env.test file.
> update readme for compose

- seta-ui/migrations/20241129000000_data_sources.py
- seta-ui/requirements.txt
- seta-ui/seta_flask_server/blueprints/admin/__init__.py
- seta-ui/seta_flask_server/blueprints/admin/data_sources.py
- seta-ui/seta_flask_server/blueprints/admin/logic/data_sources_logic.py
- seta-ui/seta_flask_server/blueprints/admin/models/data_source_dto.py
- seta-ui/seta_flask_server/blueprints/data_sources/__init__.py
- seta-ui/seta_flask_server/blueprints/data_sources/data_source.py
- seta-ui/seta_flask_server/blueprints/data_sources/models/data_source_dto.py
- seta-ui/seta_flask_server/dependency.py
- seta-ui/seta_flask_server/factory.py
- seta-ui/seta_flask_server/infrastructure/constants.py
- seta-ui/seta_flask_server/infrastructure/dto/authorizations.py
- seta-ui/seta_flask_server/repository/interfaces/__init__.py
- seta-ui/seta_flask_server/repository/interfaces/data_sources_broker.py
- seta-ui/seta_flask_server/repository/models/__init__.py
- seta-ui/seta_flask_server/repository/models/data_source.py
- seta-ui/seta_flask_server/repository/mongo_implementation/__init__.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_data_sources_broker.py
- seta-ui/tests/functional/admin/data_sources/api.py
- seta-ui/tests/functional/admin/data_sources/test_data_sources.py
Swagger doc for list view: http://localhost/seta-ui/api/v1/data-sources/doc
GET /seta-ui/api/v1/data-sources
SysAdmin API, Data Sources namespace: http://localhost/seta-ui/api/v1/admin/doc
GET, POST /seta-ui/api/v1/admin/data-sources
PUT /seta-ui/api/v1/admin/data-sources/{id}
> Api for data sources list and admin management.

- .pylintrc
- seta-admin/Dockerfile
- seta-admin/admin/config.py
- seta-admin/admin/internal/configuration.py
- seta-admin/admin/internal/interfaces/search_engine.py
- seta-admin/admin/internal/opensearch.py
- seta-admin/admin/models/index.py
- seta-admin/admin/models/response_message.py
- seta-admin/admin/routers/indexes.py
- seta-admin/logging.conf
- seta-admin/main.py
- seta-admin/requirements.txt
- seta-compose/common.yml
- seta-compose/docker-compose-test.yml
- seta-compose/docker-compose.yml
- seta-nginx/project_dev.conf
FastAPI async implementation
POST /admin/indexes - creates index
DELETE /admin/indexes/{index_name} - deletes index
In development, check docs at: 
swagger: http://localhost/admin/docs
redoc: http://localhost/admin/redoc
> seta-admin container with internal administrative web service.

- seta-ui/seta_flask_server/blueprints/admin/annotations/__init__.py
- seta-ui/seta_flask_server/blueprints/admin/annotations/annotations.py
- seta-ui/seta_flask_server/blueprints/admin/annotations/imports.py
- seta-ui/seta_flask_server/blueprints/admin/logic/annotations_logic.py
- seta-ui/seta_flask_server/blueprints/admin/models/annotation_dto.py
- seta-ui/seta_flask_server/repository/interfaces/annotations_broker.py
- seta-ui/seta_flask_server/repository/models/annotation.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_annotations_broker.py
POST /admin/annotations/import
> Import annotations - sysadmin api

- seta-nlp/main.py
- seta-ui/seta_flask_server/blueprints/admin/models/annotation_dto.py
- seta-ui/seta_flask_server/blueprints/catalogue/__init__.py
- seta-ui/seta_flask_server/blueprints/catalogue/annotations.py
- seta-ui/seta_flask_server/blueprints/catalogue/models/annotation_dto.py
http://localhost/seta-ui/api/v1/catalogue/doc
Annotations namespace
> API annotations catalogue

- .pylintrc
- seta-data/Dockerfile
- seta-doc/Dockerfile
- seta-doc/Dockerfile-dev
- seta-ui/seta_flask_server/blueprints/profile/__init__.py
- seta-ui/seta_flask_server/blueprints/profile/info.py
* set two valid routes for user profile:  /seta-ui/api/v1/me &  /seta-ui/api/v1/me/
* switch to python 3.10-slim docker image for seta-doc & seta-data
> User profile fixes

- seta-react/src/components/AppRouter/AppRouter.tsx
- seta-react/src/components/AppRouter/routes/AdminRoutes.tsx
- seta-react/src/components/Breadcrumbs/Breadcrumbs.tsx
- seta-react/src/components/GetStarted/components/Tour.tsx
- seta-react/src/components/GetStarted/steps.tsx
- seta-react/src/components/Header/Header.tsx
- seta-react/src/components/Header/components/AboutDropdown/AboutDropdown.tsx
- seta-react/src/components/Header/config.tsx
- seta-react/src/components/Header/styles.ts
- seta-react/src/layouts/AdminLayout/AdminLayout.tsx
- seta-react/src/layouts/AdminLayout/components/SidebarContent/SidebarContent.tsx
- seta-react/src/layouts/AdminLayout/components/SidebarContent/active-link.ts
- seta-react/src/pages/Admin/Datasources/Datasources.tsx
- seta-react/src/pages/Admin/Users/ManageUser/components/Permissions/components/ResourcePerms/ResourcePerms.tsx
- seta-react/src/pages/DatasourcesPage/DatasourcesPage.tsx
- seta-react/src/pages/DatasourcesPage/components/DatasourcesList/DatasourcesListContent.tsx
- seta-react/src/pages/DatasourcesPage/components/Filters/Filters.tsx
- seta-react/src/pages/FaqsPage/FaqsPage.tsx
- seta-react/src/pages/HomePage/HomePage.tsx
- seta-react/src/pages/UserProfile/CloseUserAccount/CloseUserAccount.tsx
datasource => data source in texts
datasource => data-source in routes
Breadcrumbs in admin
Set users page as init for admin console
Fix margin for 'About' menu item
> Improvements throughout the web app

- seta-react/package.json
- seta-react/pnpm-lock.yaml
- seta-ui/requirements.txt
css-what 4.0.0 -> 5.0.1
pycryptodome 3.19.0 -> 3.19.1
> Bump js and python packages

- seta-react/src/api/types/applications-permissions-types.ts
- seta-react/src/api/user/applications.ts
- seta-react/src/pages/UserProfile/Applications/components/ApplicationsList/ApplicationsList.tsx
- seta-react/src/pages/UserProfile/Applications/components/ApplicationsList/components/ApplicationRow/ApplicationRow.tsx
- seta-react/src/pages/UserProfile/Applications/components/ApplicationsList/components/UpdateApplication/components/UpdateForm/UpdateForm.tsx
- seta-react/src/pages/UserProfile/Applications/components/CreateApplication/components/CreateForm/CreateForm.tsx
- seta-react/src/pages/UserProfile/Profile/components/ExternalProviders/ExternalProviders.tsx
- seta-react/src/pages/UserProfile/Profile/components/GeneralInformation/GeneralInformation.tsx
* Name => Username on UI
* Remove user identifier
> Update UI info on user profile & applications

- seta-react/src/components/ActionIconExtended/ActionIconExtended.tsx
- seta-react/src/pages/SearchPageNew/components/SearchInput/SearchInput.tsx
- seta-react/src/pages/SearchPageNew/components/SearchInput/UploadButton.tsx
- seta-react/src/pages/SearchPageNew/components/SearchInput/styles.ts
- seta-react/src/pages/SearchPageNew/components/SuggestionsPopup/SuggestionsPopup.tsx
This PR adds the requested visual modifications to the upload button.
> [seta-react] Change Upload button UI

- .pylintrc
- seta-react/src/api/admin/annotations.ts
- seta-react/src/pages/Admin/Annotations/components/DeleteAnnotation/DeleteAnnotation.tsx
- seta-ui/seta_flask_server/blueprints/admin/annotations/annotation.py
- seta-ui/seta_flask_server/blueprints/admin/annotations/annotations.py
- seta-ui/seta_flask_server/blueprints/admin/models/annotation_dto.py
- seta-ui/seta_flask_server/repository/interfaces/annotations_broker.py
- seta-ui/seta_flask_server/repository/mongo_implementation/db_annotations_broker.py
- seta-ui/tests/functional/admin/annotations/api.py
- seta-ui/tests/functional/admin/annotations/test_annotations.py
Update admin annotations API setting category & label pair as annotation case-insensitive unique key.
> [seta-ui, seta-react] Category+label uniqueness and case-insensitive
