seta-react/.eslintrc.json, seta-react/src/components/DialogButton/DialogButton.tsx, seta-react/src/components/DocumentList/DocumentList.tsx, seta-react/src/components/FileUploads/FileUploads.tsx, seta-react/src/components/TabMenu/TabMenu.tsx, seta-react/src/components/TabMenuFilters/TabMenuFilters.tsx, seta-react/src/components/TextareaInput/TextareaInput.tsx, seta-react/src/pages/ProfilePage/ProfilePage.tsx
Optimized all `primereact` imports to target each component's module, reducing as a result the bundle size with around 40%.
Also, introduced a new ESLint rule to enforce all PrimeReact component imports from `primereact/<component>`.
There are no functional changes introduced in this PR, just make sure the app runs as expected.
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/127730071/229415441-0977e15d-a57e-4279-899f-fb5dad16a937.png)|![image](https://user-images.githubusercontent.com/127730071/229415506-b6aa0993-c73e-4c85-b0ef-8bdf918a5833.png)|
|`JS:  466.32 kB`<br>`CSS:  82.06 kB`|`JS:  269.79 kB  // ~ 42% less`<br>`CSS:  50.37 kB  // ~ 38% less`|
=> [seta-react] Optimize primereact imports & add linting rule

seta-react/package.json
This PR disables the ESLint rules evaluation for the production build.
Running the production build inside Docker with `docker compose build seta-ui-react` should succeed without errors.
=> [seta-react] Fix production build

seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/DocumentInfo.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/DocumentDetails/DocumentDetails.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/TaxonomyTree/TaxonomyNode.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/TaxonomyTree/TaxonomyTree.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/styles.ts, seta-react/src/types/search/documents.ts
This PR introduces UX improvements for the documents search results list and adjusts the taxonomy handling to match the API updates.
- Make sure you have documents indexed in ES
- Go to http://localhost/search-new or click on the Search New [WIP] menu link
- Type a few terms in the search box and press the Search button
- The list of documents should appear
- Move your mouse cursor over the header/title of a document in the list
- Verify that the header appears "interactable" to the user
- Click on the document header/title to expand its details
- Verify that expanded documents are easily identifiable
- Verify that the `Taxonomy` section, when present, is correctly represented in the UI
=> [seta-react] Update document results UX & taxonomy handling

seta-react/src/libs/axios-logger.ts, seta-react/vite.config.js
Fixes the incorrect removal of `console` and `debugger` statements during development.
Now, they should only be dropped for the production build.
- Add a `console.log` statement in any component
- Verify that it's logged in the browser's console
=> [seta-react] Fix console log removal in development

seta-react/src/App.tsx, seta-react/src/api/auth.ts, seta-react/src/components/AppRouter/AppRouter.tsx, seta-react/src/components/AppRouter/components/RequireAuth.tsx, seta-react/src/components/Header/Header.tsx, seta-react/src/contexts/user-context.tsx, seta-react/src/layouts/AppLayout/AppLayout.tsx, seta-react/src/libs/axios-error-interceptor.ts, seta-react/src/libs/axios.ts, seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OntologyHeader/OntologyHeader.tsx, seta-react/src/pages/SearchWithFilters/components/ApplyFilters/ApplyFilters.tsx, seta-react/src/pages/SearchWithFilters/components/ApplyFilters/styles.ts, seta-react/src/types/user.ts
- Added redirection to login when an API call fails
- Changed to fetch and keep the current user in a context, allowing accessing it via a custom hook
- Checking all protected routes if the user exists, otherwise redirecting to login
- Replaced the initial Search menu link with the one for the new page
- Temporarily removed the Enrich button from the suggestions dropdown
- Made a few other UI improvements
=> [seta-react] React auth improvements

seta-ui/seta_flask_server/blueprints/communities/community_membership_request.py, seta-ui/seta_flask_server/blueprints/communities/models/membership_dto.py, seta-ui/seta_flask_server/blueprints/profile/models/scopes_dto.py, seta-ui/seta_flask_server/repository/interfaces/membership_broker.py, seta-ui/seta_flask_server/repository/mongo_implementation/db_membership_broker.py
Membership requests:
* manager can get only the pending requests
* prevent updating an accepted/rejected request
* user can perform another membership request after leaving the same community
My permissions:
* fix resource_id field for the scope list
=> [seta-ui] Membership request and profile fixes

seta-react/src/api/search/documents.ts, seta-react/src/api/search/query.ts, seta-react/src/pages/SearchPageNew/SearchPageNew.tsx, seta-react/src/pages/SearchPageNew/components/SearchInput/SearchInput.tsx, seta-react/src/pages/SearchPageNew/components/SearchInput/styles.ts, seta-react/src/pages/SearchPageNew/components/SearchSuggestionInput/SearchSuggestionInput.tsx, seta-react/src/pages/SearchPageNew/components/SuggestionsPopup/SuggestionsPopup.tsx, seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/EnrichInfo/EnrichInfo.tsx, seta-react/src/pages/SearchPageNew/components/TermsSuggestions/components/OntologyHeader/OntologyHeader.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/DocumentInfo.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/styles.ts, seta-react/src/pages/SearchPageNew/components/documents/DocumentsList/DocumentsList.tsx, seta-react/src/pages/SearchPageNew/contexts/enrich-loading-context.tsx, seta-react/src/pages/SearchPageNew/types/search.ts, seta-react/src/pages/SearchPageNew/utils/search-utils.ts
This PR adds support for the `Enrich query` button.
**Important**: because the call to the enrich API with the option `enrichment_type` as `ontology` takes **a lot of time** even for a few terms, all the expansions are for the moment done as `similar`. The implementation is there but inactive - ready to be enabled once we figure out what to do on the API side for this.
Also adjusted the score display to account for the changes in the API, together with a label shown when the document is expanded.
=> [seta-react] Add Enrich support & fix documents score

seta-react/src/pages/SearchWithFilters/components/FilterInfo/FilterInfo.tsx, seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx, seta-react/src/pages/SearchWithFilters/components/FiltersPanel/status-reducer.ts
Fix clear filters for resources and taxonomies.
Disable clear all when the 'First Chunk' is the only applied filter
=> [seta-react] Fix clear filters for multiple values

seta-react/src/pages/SearchPageNew/components/SearchInput/SearchInput.tsx, seta-react/src/utils/search-utils.ts
This PR fixes two situations that made the search page fail while searching:
- Trying to search only with uploads, without any keyword
- Trying to search for something like `AND` or `OR` (or any combination of operators only, without keywords)
Also, improved a bit the Search button tooltip text when disabled.
=> [seta-react] Fix searching without keywords

seta-react/src/api/search/related-clusters.ts, seta-react/src/api/search/related-terms.ts, seta-react/src/components/Header/Header.tsx, seta-react/src/components/Header/components/NotificationsMenu.tsx, seta-react/src/layouts/AppLayout/AppLayout.tsx
This PR changes the API params used in the frontend according to the latest changes.
Also, removes the NotificationsProvider usage in AppLayout to fix the infinite reload of the login page.
=> Update API calls params & remove Notifications provider reference

seta-react/src/pages/SearchPageNew/components/SuggestionsPopup/SuggestionsPopup.tsx, seta-react/src/pages/SearchPageNew/components/upload/ChunkDetailsModal/ChunkDetailsModal.tsx, seta-react/src/pages/SearchPageNew/components/upload/UploadedDocs/UploadedDocs.tsx
This PR adds the functionality of closing the Search suggestions popup by clicking outside it, while still keeping it open when clicking on the chunk preview and confirmation modals displayed for uploaded docs/text.
=> [seta-react] Improve suggestions popup closing

seta-react/src/components/Tabs/components/TabPanel/styles.ts
This PR resolves the layout issue when the search results only contain documents with short names and chunk text.
=> Fix search results short document name alignment

seta-react/src/api/admin/users.ts, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/LibraryNode.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/LibraryTree.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/NodeActions/NodeActions.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/RootActions/RootActions.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/RootActions/index.ts, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/contexts/root-actions-context.tsx
This PR adds the Library level action for collapsing all folders.
Also, corrects an unrelated ESLint warning for the React Query key dependency inside `admin/users`.
=> [seta-react] Add Collapse All action

seta-react/src/api/search/documents.ts, seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
This PR removes the taxonomy aggregation from the Search query and the filters panel.
The code is commented out to be easily re-enabled once the API performance is fixed.
=> [seta-react] Remove taxonomy aggregations from query & filters

seta-react/src/components/SvgIcon/SvgIcon.tsx, seta-react/src/components/SvgIcon/index.ts, seta-react/src/icons/LargeArrow.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/LibraryNode.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/EmptyState/EmptyState.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/EmptyState/index.ts, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/EmptyState/styles.ts, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/NodeActions/NodeActions.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/RootActions/RootActions.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-node-content.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-node-events.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/styles.ts, seta-react/src/pages/SearchWithFilters/components/SidePanel/SidePanel.tsx, seta-react/src/utils/svg-utils.tsx
This PR implements the empty state for the Library and folder selector.
It also introduces a utility function and component to allow us to easily use SVG icons/graphics as React components.
=> [seta-react] Add empty state for the Library

seta-react/src/styles/keyframe-animations.ts, seta-react/src/utils/notifications/common.ts, seta-react/src/utils/notifications/index.ts, seta-react/src/utils/notifications/notifications.tsx, seta-react/src/utils/notifications/styles.ts
This PR introduces the `notification` utility which allows to show info, success and error notifications in a unified manner.
=> [seta-react] Add notification utils

seta-api/seta_api/infrastructure/auth_validator.py, seta-ui/seta_flask_server/blueprints/authorization/logic/token_info_logic.py, seta-ui/seta_flask_server/factory_auth.py, seta-ui/seta_flask_server/repository/interfaces/resources_broker.py, seta-ui/seta_flask_server/repository/mongo_implementation/db_resources_broker.py
Add {community_id, resource_id} in the resource_permissions list at authorization/v1//token_info endpoint.
Note: community_id is not set for 'add' and 'delete' lists.
Example:
'resource_permissions': {
'add': [{'community_id': None, 'resource_id': 'pubsy'}, {'community_id': None, 'resource_id': 'cordis'}, {'community_id': None, 'resource_id': 'seta-representative'}],
'delete': [{'community_id': None, 'resource_id': 'pubsy'}, {'community_id': None, 'resource_id': 'cordis'}, {'community_id': None, 'resource_id': 'seta-representative'}],
'view': [{'community_id': 'seta', 'resource_id': 'pubsy'}, {'community_id': 'seta', 'resource_id': 'cordis'}],
'representatives': [{'community_id': 'seta', 'resource_id': 'seta-representative'}]}
=> Add community_id info in resource permission lists

seta-react/src/api/search/export.ts, seta-react/src/api/search/library.ts, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/DocumentInfo.tsx, seta-react/src/pages/SearchPageNew/components/documents/ExportModal/ExportModal.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/contexts/tree-actions-context.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-export-modal.tsx, seta-react/src/pages/SearchPageNew/components/documents/StagedDocsPopup/StagedDocsPopup.tsx, seta-react/src/types/library/library-export.ts, seta-react/src/utils/string-utils.ts
This PR: 
- Changes the document identifier used in the Library and Staged Document to `_id`
- Adds support for exporting metadata from the Staged Documents popover
=> [seta-react] Use _id for Library docs & add Staged Docs export

seta-react/src/api/search/documents.ts, seta-react/src/pages/SearchPageNew/SearchPageNew.tsx
This PR sets the default search type to "CHUNK_SEARCH" and disables automatic refetching for the documents query.
=> [seta-react] Set default search type & disable query refetching

seta-react/src/api/search/documents.ts
This PR reverts the modifications previously done to the Search query cache options as I have identified some scenarios we need to discuss first.
=> [seta-react] Revert search query cache options

seta-react/src/pages/SearchPageNew/components/documents/DocumentsList/DocumentsList.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentsList/DocumentsListContent.tsx
This PR changes error handling for Search to show the error panel only when there is no data available in the cache.
Otherwise, the existing data remains visible and an error notification is displayed.
=> [seta-react] Keep existing data on Search error

seta-react/src/api/search/export.ts, seta-react/src/components/PromptModal/PromptModal.tsx, seta-react/src/pages/SearchPageNew/components/documents/ExportModal/ExportModal.tsx, seta-react/src/pages/SearchPageNew/components/documents/ExportModal/constants.ts, seta-react/src/pages/SearchPageNew/components/documents/ExportModal/hooks/use-export-storage.ts, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/components/NewFolderAction/NewFolderAction.tsx, seta-react/src/pages/SearchPageNew/components/documents/LibraryTree/hooks/use-rename-modal.tsx, seta-react/src/utils/library-utils.ts
This PR adds support on the front-end to export the `path` field in the Library.
=> [seta-react] Add 'path' export for Library

seta-ui/seta_flask_server/blueprints/authorization/logic/token_info_logic.py, seta-ui/seta_flask_server/blueprints/authorization/token_info.py, seta-ui/seta_flask_server/repository/interfaces/rolling_index_broker.py, seta-ui/seta_flask_server/repository/mongo_implementation/db_rolling_index_broker.py
New info added to resources permissions (check http://localhost/authorization/v1/doc).
"resource_permissions":
* "add" -> list of pairs {resource_id, indexes: list[str], limits: dict} - **one entry** indicating active storage index and storage limits for resource (size in megabytes)
Limits type: { "file_size_mb": int,  "total_files_no": int, "total_storage_mb": int     }
* "delete" -> list of pairs {resource_id, indexes: list[str]} - all storage indexes where data might reside
*
*  "view" -> list of pairs {resource_id, indexes: list[str]} - all storage indexes where data might reside
=> Resource storage indexes and limits in authorization/token_info

seta-ui/seta_flask_server/blueprints/admin/data_sources.py, seta-ui/seta_flask_server/blueprints/admin/models/data_source_dto.py, seta-ui/seta_flask_server/blueprints/data_sources/data_source.py, seta-ui/seta_flask_server/blueprints/data_sources/models/data_source_dto.py, seta-ui/seta_flask_server/blueprints/profile/__init__.py, seta-ui/seta_flask_server/blueprints/profile/models/unsearchables_dto.py, seta-ui/seta_flask_server/blueprints/profile/unsearchables.py, seta-ui/seta_flask_server/dependency.py, seta-ui/seta_flask_server/infrastructure/dto/datetime_format.py, seta-ui/seta_flask_server/repository/interfaces/__init__.py, seta-ui/seta_flask_server/repository/interfaces/user_profile_unsearchables.py, seta-ui/seta_flask_server/repository/models/__init__.py, seta-ui/seta_flask_server/repository/models/profile/__init__.py, seta-ui/seta_flask_server/repository/models/profile/unsearchables.py, seta-ui/seta_flask_server/repository/mongo_implementation/__init__.py, seta-ui/seta_flask_server/repository/mongo_implementation/profile/__init__.py, seta-ui/seta_flask_server/repository/mongo_implementation/profile/db_user_profile_unsearchables.py
New endpoint for managing unsearchable sources for user: _/me/unsearchables_.
Documentation _http://localhost/seta-ui/api/v1/me/doc_
New fields for view data source list: **created** date & **searchable** flag.
Documentation _http://localhost/seta-ui/api/v1/data-sources/doc_
=> Repository implementation for unsearchable data sources

seta-react/src/api/search/documents.ts, seta-react/src/pages/SearchPageNew/SearchPageNew.tsx, seta-react/src/pages/SearchPageNew/components/SearchResultsTabs/components/DocumentsTab/DocumentsTab.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentsList/DocumentsList.tsx, seta-react/src/pages/SearchWithFilters/components/FiltersPanel/FiltersPanel.tsx
This PR adds the following improvements:
- Removed the auto-refresh of the Search queries
- Changed to refetch the documents manually when pressing the `Search` button after the query becomes stale (5 minutes)
- Added a loading overlay over the Filters when loading while entering the page
- Fixed a bug that displayed empty filters when there was no saved search and the user changed to another page and back to Search
- Changed to move to page `1` whenever pressing the Search button
=> [seta-react] Remove search auto-refresh & add Filters loading

seta-admin/main.py, seta-nginx/project_dev.conf, seta-ui/seta_flask_server/blueprints/admin/__init__.py, seta-ui/seta_flask_server/factory.py
Fix colliding url for admin UI & internal admin service in **development**.
Swagger docs moved to [http://localhost/seta-admin/docs](http://localhost/seta-admin/docs) url.
=> Move internal admin api to /set-admin

seta-react/src/api/embeddings/embedding-info.ts, seta-react/src/api/embeddings/embedding.ts, seta-react/src/api/embeddings/file-to-text.ts, seta-react/src/environments/environment.ts, seta-react/src/libs/axios.ts
This PR splits the API calls between `seta-search` and `seta-nlp`, with the needed adjustments.
Also, some bits of dead code have been cleaned up.
Please note that `seta-api` was not removed form the Docker file.
=> [seta-react] Split Search & NLP APIs

seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/DocumentInfo.tsx, seta-react/src/pages/SearchPageNew/components/documents/DocumentInfo/components/DocumentDetails/DocumentDetails.tsx
This PR (temporarily) removes the Taxonomies section from the documents list on the Search results.
=> [seta-react] Remove Taxonomies from documents list
